### ISSUE TITLE
Lockup when deleting audio functions

### ISSUE THREAD

**Issue by matthijskooijman** [mcallegari/qlcplus#1068]
Originally noticed on QLC 4.11.2 (qt4), reproduced with current git master (67fa5bef, als linked against qt4), running on Debian Linux Stretch amd64. This was [previously reported on the forum too](http://www.qlcplus.org/forum/viewtopic.php?t=10496).

To reproduce:
 1. Create a new workspace
 2. Add an audio function
 3. Save the workspace, restart qlcplus and reload the workspace.
 4. Delete the audio function.

After this, qlc becomes unresponsive.

I've attached a [workspace](https://github.com/mcallegari/qlcplus/files/2089510/Audiocrash.txt) (renamed to .txt to fool github) with steps 1-3 applied already. It is not needed for the audio file to actually exist (the crash happens with and without the actual file).

Running under gdb suggests there is some locking deadlock. The main thread seems to be waiting for a lock. When I interrupt gdb while qlc is unresponsive, I get the following backtraces. The backtrace for thread 1 seems unchanged when I continue and interrupt again later. I'm not sure how to get more details about what lock this is (and more importantly, who is holding the lock).

```
(gdb) thread apply all bt                                                      
                         
Thread 9 (Thread 0x7fff5729f700 (LWP 22322)):
#0  0x00007ffff4c285d9 in __GI___poll (fds=0x5555561edec0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff39b59f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0                                           
#2  0x00007ffff39b5d82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffed762656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0          
#4  0x00007ffff39dd3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0   
#5  0x00007ffff582d5aa in start_thread (arg=0x7fff5729f700) at pthread_create.c:463
#6  0x00007ffff4c32cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 
                                                                                  
Thread 8 (Thread 0x7fff5f25d700 (LWP 22321)):
#0  0x00007ffff4c285d9 in __GI___poll (fds=0x5555561edaa0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff39b59f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0                                           
#2  0x00007ffff39b5b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff39b5b51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0                      
#4  0x00007ffff39dd3d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff582d5aa in start_thread (arg=0x7fff5f25d700) at pthread_create.c:463
#6  0x00007ffff4c32cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 
                                                                                  
Thread 7 (Thread 0x7fff5d754700 (LWP 22320)):
#0  0x00007ffff58372e0 in __GI___nanosleep (requested_time=0x7fff50004a20, remaining=0x7fff50004a00) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff7b60499 in MasterTimerPrivate::run (this=0x555555a30880) at mastertimer-unix.cpp:178                                              
#2  0x00007ffff5abedaa in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4                      
#3  0x00007ffff582d5aa in start_thread (arg=0x7fff5d754700) at pthread_create.c:463
#4  0x00007ffff4c32cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 
                                                                                  
Thread 2 (Thread 0x7fffe09ec700 (LWP 22308)):
#0  0x00007ffff58334ec in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffff70d0fb8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88                                                           
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7ffff70d0f68, cond=0x7ffff70d0f90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7ffff70d0f90, mutex=0x7ffff70d0f68) at pthread_cond_wait.c:655                    
#3  0x00007ffff6dbd61a in ?? () from /usr/lib/x86_64-linux-gnu/libQtScript.so.4               
#4  0x00007ffff6dbd649 in ?? () from /usr/lib/x86_64-linux-gnu/libQtScript.so.4
#5  0x00007ffff582d5aa in start_thread (arg=0x7fffe09ec700) at pthread_create.c:463
#6  0x00007ffff4c32cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 
                                                                                  
Thread 1 (Thread 0x7ffff7f877c0 (LWP 22304)):
#0  0x00007ffff4c1a6c7 in sched_yield () at ../sysdeps/unix/syscall-template.S:78
#1  0x00007ffff5ab97dd in QMutex::lockInternal() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#2  0x00007ffff7abeaa4 in QMutex::lockInline (this=0x5555560caa80) at /usr/include/qt4/QtCore/qmutex.h:198
#3  0x00007ffff7abe9d3 in QMutexLocker::QMutexLocker (this=0x7fffffffce90, m=0x5555560caa80) at /usr/include/qt4/QtCore/qmutex.h:109
#4  0x00007ffff7b0c318 in Function::stop (this=0x5555560caa00, source=...) at function.cpp:1134           
#5  0x00007ffff74c30d3 in AudioEditor::~AudioEditor (this=0x5555561473d0, __in_chrg=<optimized out>) at audioeditor.cpp:125         
#6  0x00007ffff74c3100 in AudioEditor::~AudioEditor (this=0x5555561473d0, __in_chrg=<optimized out>) at audioeditor.cpp:126
#7  0x00007ffff5be93a8 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4                         
#8  0x00007ffff61522ec in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4                          
#9  0x00007ffff60fb54c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007ffff610252c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007ffff5bcef1d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4 
#12 0x00007ffff5bd2a16 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007ffff5bff703 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4                                                 
#14 0x00007ffff39b57f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0                                                 
#15 0x00007ffff39b5a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0  
#16 0x00007ffff39b5b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff5bff854 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007ffff61a55d6 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4                     
#19 0x00007ffff5bcd7ef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4          
#20 0x00007ffff5bcdb55 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007ffff5bd3bd9 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4                                        
#22 0x00005555555583f8 in main (argc=1, argv=0x7fffffffd818) at main.cpp:387             
```

Running under `valgrind --tool=helgrind` (I needed the version from Debian/unstable, the one from stable errors out on an unsupported REPZ NOP instruction on startup) shows a ton of warnings while starting up until the display of the "are you sure?" dialog, but once I press "yes" to delete the audio file, a segfault is triggered (which does not happen outside helgrind) without any lock-related error messages:
```
==30827== Process terminating with default action of signal 11 (SIGSEGV)
==30827==  General Protection Fault
==30827==    at 0x6E09A35: ref (qatomic_x86_64.h:121)
==30827==    by 0x6E09A35: QString (qstring.h:726)
==30827==    by 0x6E09A35: putString (qtextstream.cpp:968)
==30827==    by 0x6E09A35: QTextStream::operator<<(QString const&) (qtextstream.cpp:2533)
==30827==    by 0x4EF522F: QDebug::operator<<(QString const&) (qdebug.h:112)
==30827==    by 0x4F682B3: Function::stop(FunctionParent) (function.cpp:1132)
==30827==    by 0x53AF0D2: AudioEditor::~AudioEditor() (audioeditor.cpp:125)
==30827==    by 0x53AF0FF: AudioEditor::~AudioEditor() (audioeditor.cpp:126)
==30827==    by 0x6E863A7: QObject::event(QEvent*) (qobject.cpp:1203)
==30827==    by 0x620E2EB: QWidget::event(QEvent*) (qwidget.cpp:8859)
==30827==    by 0x61B754B: QApplicationPrivate::notify_helper(QObject*, QEvent*) (qapplication.cpp:4570)
==30827==    by 0x61BE52B: QApplication::notify(QObject*, QEvent*) (qapplication.cpp:4356)
==30827==    by 0x6E6BF1C: QCoreApplication::notifyInternal(QObject*, QEvent*) (qcoreapplication.cpp:955)
==30827==    by 0x6E6FA15: sendEvent (qcoreapplication.h:231)
==30827==    by 0x6E6FA15: QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (qcoreapplication.cpp:1579)
==30827==    by 0x6E9C702: sendPostedEvents (qcoreapplication.h:236)
==30827==    by 0x6E9C702: postEventSourceDispatch(_GSource*, int (*)(void*), void*) (qeventdispatcher_glib.cpp:280)
```

Trying to run under `mutextrace` segfaults directly at startup.

I'm happy to try other debug approaches, if you have suggestions.

**Comment by matthijskooijman** [comment]
Hm, I assumed QT4 was still the default, based on the fact that the normal Ubuntu .deb release uses qt4. I tested with QT5 (both my own git master build and the OpenSuse Ubuntu build of 4.11.2), and that seems to work fine... Oh well :-)
