### ISSUE TITLE
Segfault after start on openSUSE tumbleweed

### ISSUE THREAD

**Issue by nettings** [mcallegari/qlcplus#436]
After a bit of massaging, I got qlcplus git HEAD from 2015-01-15 to build, but it segfaults immediately after startup in a Qt call. Here's a backtrace in the hope that it's useful:

nettings@hoppetosse:/local/build/qlcplus> gdb qlcplus
...
(gdb) run
Starting program: /usr/bin/qlcplus 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.20-2.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe5040700 (LWP 29318)]
[New Thread 0x7fffe483f700 (LWP 29319)]
[New Thread 0x7fffdffff700 (LWP 29320)]
[New Thread 0x7fffdf7fe700 (LWP 29321)]

Q Light Controller Plus version 4.8.4 GIT
This program is licensed under the terms of the Apache 2.0 license.
Copyright (c) Heikki Junnila (hjunnila@users.sf.net)
Copyright (c) Massimo Callegari (massimocallegari@yahoo.it)

[New Thread 0x7fffdd19a700 (LWP 29323)]
[Thread 0x7fffdf7fe700 (LWP 29321) exited]
[New Thread 0x7fffdf7fe700 (LWP 29325)]
[New Thread 0x7fff48873700 (LWP 29326)]
[New Thread 0x7fff475f7700 (LWP 29327)]

Program received signal SIGSEGV, Segmentation fault.
0x00000000004045c0 in QBasicAtomicInt::deref (this=0x3e004c004d) at /usr/include/QtCore/qatomic_x86_64.h:133
133	                 : "memory");
...
...
Thread 1 (Thread 0x7ffff7f947c0 (LWP 29314)):
#0  0x00000000004045c0 in QBasicAtomicInt::deref() (this=0x3e004c004d) at /usr/include/QtCore/qatomic_x86_64.h:133
#1  0x00000000004047c9 in QString::~QString() (this=0xa87890, __in_chrg=<optimized out>) at /usr/include/QtCore/qstring.h:880
#2  0x00000000004051d1 in QList<QString>::node_destruct(QList<QString>::Node*, QList<QString>::Node*) (this=0x7fffffffcd50, from=0xa878e8, to=0xa87890)
    at /usr/include/QtCore/qlist.h:433
#3  0x0000000000404ed7 in QList<QString>::free(QListData::Data*) (this=0x7fffffffcd50, data=0xa87860) at /usr/include/QtCore/qlist.h:757
#4  0x0000000000404c4e in QList<QString>::~QList() (this=0x7fffffffcd50, __in_chrg=<optimized out>) at /usr/include/QtCore/qlist.h:732
#5  0x0000000000404af6 in QStringList::~QStringList() (this=0x7fffffffcd50, __in_chrg=<optimized out>) at /usr/include/QtCore/qstringlist.h:66
#6  0x00007ffff75abae3 in InputOutputPatchEditor::fillMappingTree() (this=0xad33e0) at inputoutputpatcheditor.cpp:345
#7  0x00007ffff75aa793 in InputOutputPatchEditor::setupMappingPage() (this=0xad33e0) at inputoutputpatcheditor.cpp:182
#8  0x00007ffff75aa308 in InputOutputPatchEditor::InputOutputPatchEditor(QWidget*, unsigned int, InputOutputMap*, Doc*) (this=0xad33e0, parent=0xcd1560, universe=0, ioMap=0x8319b0, doc=0x840f10) at inputoutputpatcheditor.cpp:130
#9  0x00007ffff75a954e in InputOutputManager::slotCurrentItemChanged() (this=0xcd1560) at inputoutputmanager.cpp:313
#10 0x00007ffff76e6bf5 in InputOutputManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0xcd1560, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7fffffffd300) at moc_inputoutputmanager.cpp:69
#11 0x00007ffff5a6322a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib64/libQtCore.so.4
#12 0x00007ffff64e95cb in QListWidget::currentItemChanged(QListWidgetItem*, QListWidgetItem*) () at /usr/lib64/libQtGui.so.4
#13 0x00007ffff64e96dc in  () at /usr/lib64/libQtGui.so.4
#14 0x00007ffff5a6322a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib64/libQtCore.so.4
#15 0x00007ffff64d82ca in QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&) () at /usr/lib64/libQtGui.so.4
#16 0x00007ffff64d83ad in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) ()
    at /usr/lib64/libQtGui.so.4
#17 0x00007ffff64e8b78 in QListWidget::setCurrentRow(int) () at /usr/lib64/libQtGui.so.4
#18 0x00007ffff75a8896 in InputOutputManager::updateList() (this=0xcd1560) at inputoutputmanager.cpp:212
#19 0x00007ffff75a80b8 in InputOutputManager::InputOutputManager(QWidget*, Doc*) (this=0xcd1560, parent=0x82a750, doc=0x840f10)
    at inputoutputmanager.cpp:163
#20 0x00007ffff7513967 in App::init() (this=0x7fffffffdc70) at app.cpp:256
#21 0x00007ffff7512ec5 in App::startup() (this=0x7fffffffdc70) at app.cpp:168
---Type <return> to continue, or q <return> to quit---
#22 0x000000000040422d in main(int, char**) (argc=1, argv=0x7fffffffde98) at main.cpp:328
(gdb)

**Comment by nettings** [comment]
Looks like this was due to zombie code from a previous compilation run. Manually clearing /usr/lib/qt4/plugins/qlcplus and reinstalling fixed the issue. Sorry for the noise, it starts fine now.
